name: Deploy branch master to server

on:
  push:
    branches:
      - 'develop'

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Merge to develop server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP_ADDRESS_DEVELOP }}
          sync: true
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE }}
          port: ${{ secrets.SSH_PORT }}
          script: ./busanid_back.sh
